development:
  adapter: postgresql
  encoding: utf8
  database: db/project_development
  pool: 5
  timeout: 5000
  username: rhlobo
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: db/project_test
  pool: 5
  timeout: 5000
  username: rhlobo
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: db/project_production
  pool: 5
  timeout: 5000

cucumber:
  <<: *TEST